version: "3"
services:
  blackjack:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /projblackjackect
    volumes:
      - .:/blackjack
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: blackjack-image
    container_name: blackjack-container
    tty: true
    env_file: .env # shellスクリプト内でも環境変数として使用するため
