name: pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up python
        uses: ./.github/actions/python_setup
      - name: set up poetry
        uses: ./.github/actions/poetry_setup
      - name: Test with pytest
        run: |
          source .venv/bin/activate
          pytest
